"""added PostLike model and relationships

Revision ID: 21caacca8c1a
Revises: a4eb6356541a
Create Date: 2020-06-09 16:43:42.680026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21caacca8c1a'
down_revision = 'a4eb6356541a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_like')
    # ### end Alembic commands ###
