"""Added image_file field to Post model

Revision ID: df1a8d40af36
Revises: 21caacca8c1a
Create Date: 2020-06-16 15:29:10.312537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1a8d40af36'
down_revision = '21caacca8c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_file')
    # ### end Alembic commands ###
